### ISSUE TITLE
getProductById method returns an empty image array and description

### ISSUE THREAD

**Issue by AnikDey-exe** [rye-com/rye-sdk#14]
We are using the rye-api sdk for our express backend and this is how we are calling the getProductById method:
```
const productInfo = await ryeClient.getProductById({
                input: {
                    id: productID,
                    // @ts-ignore
                    marketplace: "AMAZON",
                }
            });
```
This is our import statement in the same file:
`import ryeClient from '@/lib/ryeClient';`

lib/ryeClient.ts:
```
import { RyeClient, ENVIRONMENT } from "@rye-api/rye-sdk";
import * as dotenv from 'dotenv';

dotenv.config();

const ryeClient = new RyeClient({
    authHeader: process.env.RYE_AUTH_HEADER || <KEY>,
    shopperIp: process.env.RYE_SHOPPER_IP || <KEY>,
    environment: ENVIRONMENT.STAGING,
});

export default ryeClient;
```

However, the object returned from getProductById most of the time has an empty images array and description. Is this a bug on rye's end or are we doing something wrong?

**Comment by sophiabits** [comment]
Are you calling `requestProductByUrl` prior to `getProductById`?

If you try to retrieve data for an Amazon product without first requesting it, you will only receive partial data.

If you _are_ requesting before calling `getProductById`, then you might be running into timing issues. It takes up to ~18s for an Amazon product's data to become fully available. If you call `getProductById` after this period of time (and after having called `requestProductByUrl`) then you should see all of the fields come through as expected.

**Comment by AnikDey-exe** [comment]
I’m calling requestProductByUrl before

**Comment by AnikDey-exe** [comment]
Wouldn’t that be slow on the clients end for them to wait ~18 seconds before the product loads?

**Comment by sophiabits** [comment]
Yes it would, but unfortunately this is a known limitation of our API. We want to speed this up, but don’t have an ETA on when that will happen.

If response time is important for your use case and you can find another API that returns product data faster, then one option would be to requestProductByUrl and return that other API’s product data while waiting for Rye to index it.
