### ISSUE TITLE
requestStoreByURL

### ISSUE THREAD

**Issue by vulus98** [rye-com/rye-sdk#16]
I am trying to programmatically get the canonicalURL of a shop by using a storefront one, but everything I make a request like this
```
 let ryeSecrets!: RyeSecrets;
    let ryeClient!: RyeClient;
    const environment = ENVIRONMENT.PRODUCTION;
    ryeSecrets = JSON.parse(await accessSecret("rye"));
    ryeClient = new RyeClient(
        `Basic ${environment === ENVIRONMENT.PRODUCTION ? ryeSecrets.RYE_API_KEY_PROD : ryeSecrets.RYE_API_KEY_STAGING}`,
        ryeSecrets.RYE_SHOPPER_IP,
        environment,
      );
const result = await ryeClient.requestStoreByUrl({
      input: {
        url: storefrontURL,
      },
    });
 ```
 
 I get the result being undefined. It seems I am following the example you provided in the SDK, but it is not working for some reason. Running the same thing for the same URL in Rye console works.

**Comment by foreverest** [comment]
Hey @vulus98. If you receive an undefined response, it probably means the GraphQL response has a null `data` field and a non-null `errors` one. Unfortunately, the current version of the SDK does not allow you to see what the errors are. We will fix this in a future version.

I could reproduce the issue when I provided an incorrect value for `authHeader`. Please make sure your `ryeSecrets.RYE_API_KEY_PROD` value is correct.
